### ISSUE TITLE
Suggestion: Set base font size to percentage rather than pixel value

### ISSUE THREAD

**Issue by denno020** [beercss/beercss#38]
The current base font size that all `rem` values are based on is `1px`, set on the `html` element. This causes an issue for users with vision impairment who increase the font size in their browser when browsing websites - websites that are based on a pixel value won't change.

**Demonstration**
The following animation shows what happens to the BeerCSS page when changing the font size within a browsers settings.
![BeerCSS Text not changing](https://user-images.githubusercontent.com/2059313/152663152-ed197e94-618b-4c92-91bd-5797c8b80730.gif)

As we can see, nothing happens.

With 1 single change to the code, setting `--size` to be `6.25%`, we get the following:

![BeerCSS Text changing](https://user-images.githubusercontent.com/2059313/152663164-8857d9ba-231c-4202-a2d2-38af7e816190.gif)

As we can see, changing the font size will change the BeerCSS page, with the text getting bigger. A lot of the layout also changes, which I personally wouldn't want - I would only want the typography to change - but to rectify that behaviour we would need to refactor quite a bit of the code, as all sizes seem to be based on `rem`.

The 6.25% value is determine by dividing the pixel equivalent that we want (1px) by the default font size in browsers (16px), then multiplying it by 100: `1 / 16 = 0.0625 * 100 = 6.25`

I think it would be great to have BeerCSS taking on a11y approaches, asit will have a positive affect on users who visit websites built using Beer.

**Comment by leonardorafael** [comment]
Great @denno020 , 

We will change the root to percent to work like expected. I'm not the right guy to talk about a11y here 🙁. If we do not use the same unit (px, rem, em) in all elements (only in typography) It can cause some design, aspect ratio and overflow issues on containers. But we think about it in future, ok? 👍

**Comment by leonardorafael** [comment]
@denno020 can you do a PR to change the root to percent?

**Comment by leonardorafael** [comment]
Done in v2.0.9 https://github.com/beercss/beercss/releases/tag/v2.0.9

**Comment by denno020** [comment]
@leonardorafael Great to see that the base font-size has been updated to match the browser default, however the accesibility issue is still present.. By setting the base font to `16px`, we're ignoring the browsers default font size. Rather, we should default `--size` to `1rem` ourselves (or even not defining it, but probably makes more sense for it to at least have a value).
